---
hero_image: images/banner.png
title: Створи власний світ
description: Створи свою власну пригодницьку гру в жанрі «Відкритий світ»
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - title: Вступ
  - title: Переміщення спрайта гравця
  - title: Стіни
    completion:
      - engaged
  - title: Переміщення по світу
  - title: 'Завдання: повернутися в попередню кімнату'
    challenge: true
  - title: Таблички
  - title: 'Завдання: скарб!'
    challenge: true
  - title: Люди
  - title: 'Завдання: противники'
    challenge: true
  - title: Збирання монет
  - title: Двері та ключі
    completion:
      - internal
  - title: 'Завдання: розшир свій світ'
    challenge: true
  - title: Що далі?
