---
hero_image: images/banner.png
title: Maak je eigen wereld
description: Leer hoe je je eigen open-wereld avonturenspel kunt maken
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
- title: Inleiding
  completion: engaged
- title: De sprite van de speler verplaatsen
- title: Stevige muren
- title: Verplaats je door je wereld
- title: 'Uitdaging: ga naar de vorige kamer'
  challenge: true
- title: Borden
- title: 'Uitdaging: schat!'
  challenge: true
- title: Personen
- title: 'Uitdaging: voeg een vijand toe'
  challenge: true
- title: Munten verzamelen
  completion: internal
- title: Deuren en sleutels
- title: 'Uitdaging: vergroot je wereld'
  challenge: true
- title: Wat nu?
