---
hero_image: images/create-your-own-world.png
title: Maak je eigen wereld
description: Leer hoe je je eigen openwereld adventure-spel kunt maken.
listed: true
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Wat je nodig hebt
  - 
    title: De sprite van de speler verplaatsen
  - 
    title: Stevige muren
  - 
    title: "Programmeer je wereld"
    challenge: true
  - 
    title: Borden
  - 
    title: "Uitdaging: schat!"
    challenge: true
  - 
    title: Personen
  - 
    title: "Uitdaging: vijanden"
    challenge: true
  - 
    title: Munten verzamelen
  - 
    title: Deuren en sleutels
  - 
    title: "Uitdaging: vergroot je wereld"
    challenge: true
  - 
    title: "What next?"
