---
hero_image: images/banner.png
title: आपला स्वतःचा गेम तयार करा
description: आपला स्वतःचा ओपन-वर्ल्ड अ‍ॅडव्हेंचर गेम तयार करा
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
- title: परिचय
- title: तुमचा खेळाडू (player) sprite ला हलवा
- title: भरीव भिंती
  completion:
  - engaged
- title: तुमच्या गेमच्या जगात फिरा
- title: 'आव्हान: मागील खोलीकडे परत जा'
  challenge: true
- title: चिन्हे
- title: 'आव्हान: खजिना!'
  challenge: true
- title: लोक
- title: 'आव्हान: शत्रू'
  challenge: true
- title: नाणी गोळा करा
- title: दारे आणि चाबी
  completion:
  - internal
- title: 'आव्हान: तुमचे जग वाढवा'
  challenge: true
- title: पुढे काय?
