---
hero_image: images/banner.png
title: Создай свой собственный мир
description: Создайте свою собственную игру с открытым миром
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
- title: Введение
  completion: engaged
- title: Перемещение спрайта игрока
- title: Сплошные стены
- title: Перемещение по миру
- title: 'Задача: вернуться в предыдущую комнату'
  challenge: true
- title: Таблички
- title: 'Задача: сокровище!'
  challenge: true
- title: Люди
- title: 'Задача: враги'
  challenge: true
- title: Сбор монет
  completion: internal
- title: Двери и ключи
- title: 'Задача: расширь свой мир'
  challenge: true
- title: Что дальше?
