---
hero_image: images/banner.png
title: अपनी स्वयं की दुनिया बनाएँ
description: अपना स्वयं का ओपन-वर्ल्ड एडवेंचर गेम बनाना सीखें।
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: भूमिका
  - 
    title: आपको किसकी ज़रूरत होगी
  - 
    title: खिलाड़ी की स्प्राइट को स्थानांतरित करना
  - 
    title: Move around your world
  - 
    title: "Challenge: move back to the previous room"
    challenge: true
  - 
    title: संकेत
  - 
    title: "चुनौती: खज़ाना!"
    challenge: true
  - 
    title: लोग
  - 
    title: "चुनौती: दुश्मन"
    challenge: true
  - 
    title: कॉइन एकत्र करना
  - 
    title: Doors and keys
  - 
    title: "चुनौती: अपनी दुनिया को बढ़ाएं"
    challenge: true
  - 
    title: "आगे क्या?"
