---
hero_image: images/banner.png
title: अपनी दुनिया बनाएँ
description: अपना चाभियाँ ओपन-वर्ल्ड एडवेंचर (open-world adventure) गेम बनाना सीखें।
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
- title: परिचय
  completion: engaged
- title: खिलाडी स्प्राइट (player sprite) को हिलाएं
- title: पक्की दीवारें
- title: अपनी दुनिया में घूमें
- title: 'चुनौती: पिछले कमरे में वापस जाएँ'
  challenge: true
- title: संकेत (Signs)
- title: 'चुनौती: खज़ाना!'
  challenge: true
- title: लोग
- title: 'चुनौती: दुश्मन'
  challenge: true
- title: कोइन्स (Coins) बटोरना
  completion: internal
- title: दरवाज़े और चाभियाँ
- title: 'चुनौती: अपनी दुनिया को और भी बड़ा बनाएं'
  challenge: true
- title: आगे क्या?
