---
hero_image: images / create-your-own-world.png
title: あなた自身の世界を作りなさい
description: Create your own open-world adventure game
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: 前書き
  - 
    title: Move the player sprite
  - 
    title: Solid walls
  - 
    title: Move around your world
  - 
    title: "Challenge: move back to the previous room"
    challenge: true
  - 
    title: サイン
  - 
    title: "挑戦：宝物！"
    challenge: true
  - 
    title: 人
  - 
    title: "挑戦：敵"
    challenge: true
  - 
    title: Collect coins
  - 
    title: ドアとキー
  - 
    title: "課題：あなたの世界を広げる"
    challenge: true
  - 
    title: "What next?"
