---
hero_image: images/banner.png
title: Cria o teu próprio mundo
description: Criar o teu próprio jogo de aventura no open-world
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: Introdução
  - 
    title: Mover o personagem do jogador
  - 
    title: Paredes sólidas
    completion:
      - engaged
  - 
    title: Mova-se pelo seu mundo
  - 
    title: 'Desafio: voltar para a sala anterior'
    challenge: true
  - 
    title: Sinais
  - 
    title: 'Desafio: tesouro!'
    challenge: true
  - 
    title: Pessoas
  - 
    title: 'Desafio: inimigos'
    challenge: true
  - 
    title: Recolher moedas
  - 
    title: Portas e chaves
    completion:
      - internal
  - 
    title: 'Desafio: amplia o teu mundo'
    challenge: true
    completion:
      - external
