---
hero_image: images/create-your-own-world.png
title: 建你自己的世界
description: 建自己的冒险游戏
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: 介绍
  - 
    title: 移动玩家
  - 
    title: 坚固的墙壁
  - 
    title: 走动你的世界
  - 
    title: "挑战：回到上一个房间"
    challenge: true
  - 
    title: 标志
  - 
    title: "挑战：宝藏！"
    challenge: true
  - 
    title: 人物
  - 
    title: "挑战：敌人"
    challenge: true
  - 
    title: 收集硬币
  - 
    title: 门和钥匙
  - 
    title: "挑战：扩展你的世界"
    challenge: true
  - 
    title: "接下来还有什么？"
