---
hero_image: images/create-your-own-world.png
title: Kreiraj vlastiti svijet
description: U ovom projektu naučit ćeš napraviti vlastitu igricu avanture.
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: Sretan rođendan
  - 
    title: Pomicanje sprite igrača
  - 
    title: Čvrsti zidovi
    completion:
      - engaged
  - 
    title: Kreći se svojim svijetom
  - 
    title: 'Izazov: vratite se u prethodnu sobu'
    challenge: true
  - 
    title: Znakovi
  - 
    title: 'Izazov: blago!'
    challenge: true
  - 
    title: Ljudi
  - 
    title: 'Izazov: neprijatelji'
    challenge: true
  - 
    title: Skupljaj kovanice
  - 
    title: Vrata i ključevi
    completion:
      - internal
  - 
    title: 'Izazov: proširi svoj svijet'
    challenge: true
    completion:
      - external
