---
hero_image: images/create-your-own-world.png
title: Crea tu propio mundo
description: Aprende a crear tu propio juego de aventura mundial.
listed: true
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Programar a tu jugador
  - 
    title: Programar tu mundo
  - 
    title: Señales
  - 
    title: "Personas"
    challenge: true
  - 
    title: Señales
  - 
    title: "Desafío: ¡Un tesoro!"
    challenge: true
  - 
    title: Personas
  - 
    title: "Desafío: Enemigos"
    challenge: true
  - 
    title: Collect coins
  - 
    title: Puertas y llaves
  - 
    title: "Desafío: Amplía tu mundo"
    challenge: true
  - 
    title: "What next?"
