---
hero_image: images/banner.png
title: Crea tu propio mundo
description: Aprende a crear tu propio juego de aventura mundial.
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: Introducción
  - 
    title: Programar a tu jugador
  - 
    title: Paredes macizas
  - 
    title: Señales
  - 
    title: "Personas"
    challenge: true
  - 
    title: Señales
  - 
    title: "Desafío: ¡Un tesoro!"
    challenge: true
  - 
    title: Personas
  - 
    title: "Desafío: Enemigos"
    challenge: true
  - 
    title: Recoger monedas
  - 
    title: Puertas y llaves
  - 
    title: "Desafío: Amplía tu mundo"
    challenge: true
  - 
    title: "Desafío: más colores"
