---
hero_image: images/create-your-own-world.png
title: Creu dy fyd dy hunan
description: Dysga sut i greu gêm antur
listed: true
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Codio dy chwareuwr
  - 
    title: Waliau cadarn
  - 
    title: Symud o gwmpas dy fyd
  - 
    title: "Her: symud yn ôl i'r ystafell flaenorol"
    challenge: true
  - 
    title: Arwyddion
  - 
    title: "Her: trysor!"
    challenge: true
  - 
    title: Pobl
  - 
    title: "Her: gelynion"
    challenge: true
  - 
    title: Casglu darnau arian
  - 
    title: Drysau ac allweddi
  - 
    title: "Her: ymestyn dy fyd"
    challenge: true
  - 
    title: "Beth nesaf?"
