---
hero_image: images/create-your-own-world.png
title: Creu dy fyd dy hunan
description: Dysga sut i greu gêm antur
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
- title: Cyflwyniad
  completion: engaged
- title: Symud dy chwareuwr
- title: Waliau cadarn
- title: Symud o gwmpas dy fyd
- title: 'Her: symud yn ôl i''r ystafell flaenorol'
  challenge: true
- title: Arwyddion
- title: 'Her: trysor!'
  challenge: true
- title: Pobl
- title: 'Her: ychwanegu gelyn'
  challenge: true
- title: Casglu darnau arian
  completion: internal
- title: Drysau ac allweddi
- title: 'Her: ymestyn dy fyd'
  challenge: true
- title: Beth nesaf?
