---
hero_image: images/banner.png
title: Erschaffe deine eigene Welt
description: Lerne, wie du dein eigenes Open-World Abenteuerspiel erstellen kannst
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
- title: Einleitung
- title: Programmiere deinen Spieler
- title: Massive Wände
  completion:
  - engaged
- title: Bewege dich in deiner Welt
- title: 'Herausforderung: Zurück zum vorherigen Raum'
  challenge: true
- title: Schilder
- title: 'Herausforderung: Der Schatz!'
  challenge: true
- title: Personen
- title: 'Herausforderung: Einen Gegner hinzufügen'
  challenge: true
- title: Münzen sammeln
- title: Türen und Schlüssel
  completion:
  - internal
- title: 'Herausforderung: Erweitere deine Welt'
  challenge: true