---
hero_image: images/create-your-own-world.png
title: Erschaffe deine eigene Welt
description: Lerne, wie du dein eigenes Open-World Abenteuerspiel programmieren kannst.
original_url: https://codeclubprojects.org/en-GB/scratch/create-your-own-world
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Den Spieler bewegen
  - 
    title: Schilder
  - 
    title: Leute
  - 
    title: Münzen sammeln
  - 
    title: 'Türen und Schlüssel'
  - 
    title: Leute
  - 
    title: 'Herausforderung: Feinde'
  - 
    title: Münzen sammeln
  - 
    title: Türen und Schlüssel
  - 
    title: 'Herausforderung: Erweitere deine Welt'
