---
hero_image: images/create-your-own-world.png
title: Erschaffe deine eigene Welt
description: Lerne, wie du dein eigenes Open-World Abenteuerspiel erstellen kannst.
listed: true
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Programmiere deinen Spieler
  - 
    title: Programmiere deine Welt
  - 
    title: Schilder
  - 
    title: "Leute"
    challenge: true
  - 
    title: Schilder
  - 
    title: "Herausforderung: Der Schatz!"
    challenge: true
  - 
    title: Personen
  - 
    title: "Herausforderung: Feinde"
    challenge: true
  - 
    title: Collect coins
  - 
    title: Türen und Schlüssel
  - 
    title: "Herausforderung: Erweitere deine Welt"
    challenge: true
  - 
    title: "What next?"
