---
hero_image: images/banner.png
title: Crează-ți propria lume
description: Crează-ți propriul joc de aventură
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: Introducere
  - 
    title: Mută personajul
  - 
    title: Pereți solizi
  - 
    title: Mișcă-te în jurul lumii tale
  - 
    title: "Provocare: întoarce-te în camera precedentă"
    challenge: true
  - 
    title: Semne
  - 
    title: "Provocare: comoară!"
    challenge: true
  - 
    title: Persoane
  - 
    title: "Provocare: inamici"
    challenge: true
  - 
    title: Adună monede
  - 
    title: Uși și chei
  - 
    title: "Provocare: extinde-ți lumea"
    challenge: true
  - 
    title: "Ce urmează?"
