---
hero_image: images/create-your-own-world.png
title: Crie seu próprio mundo
description: Neste projeto, você aprenderá como criar o seu próprio jogo de aventura em mundo aberto.
listed: true
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Crie seu próprio mundo
  - 
    title: Move the player sprite
  - 
    title: Solid walls
  - 
    title: Move around your world
  - 
    title: "Challenge: move back to the previous room"
    challenge: true
  - 
    title: Signs
  - 
    title: "Challenge: treasure!"
    challenge: true
  - 
    title: People
  - 
    title: "Challenge: enemies"
    challenge: true
  - 
    title: Collect coins
  - 
    title: Doors and keys
  - 
    title: "Challenge: extend your world"
    challenge: true
  - 
    title: "What next?"
