---
hero_image: images/create-your-own-world.png
title: Crie seu próprio mundo
description: Neste projeto, você aprenderá como criar o seu próprio jogo de aventura em mundo aberto.
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: Introdução
  - 
    title: Mover o sprite do jogador
  - 
    title: Paredes sólidas
  - 
    title: Mova-se ao redor do seu mundo
  - 
    title: "Desafio: voltar à sala anterior"
    challenge: true
  - 
    title: Sinais
  - 
    title: "Desafio: tesouro!"
    challenge: true
  - 
    title: Pessoas
  - 
    title: "Desafio: inimigos"
    challenge: true
  - 
    title: Recolha moedas
  - 
    title: Portas e chaves
  - 
    title: "Desafio: estenda seu mundo"
    challenge: true
  - 
    title: "E agora?"
