---
hero_image: images/banner.png
title: Crie seu próprio mundo
description: Neste projeto, você aprenderá como criar o seu próprio jogo de aventura
  em mundo aberto.
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
- title: Introdução
  completion: engaged
- title: Mova o ator do jogador
- title: Paredes sólidas
- title: Mova-se pelo seu mundo
- title: 'Desafio: voltar para a sala anterior'
  challenge: true
- title: Sinalizações
- title: 'Desafio: tesouro!'
  challenge: true
- title: Pessoas
- title: 'Desafio: inimigos'
  challenge: true
- title: Coletar moedas
  completion: internal
- title: Portas e chaves
- title: 'Desafio: expanda seu mundo'
  challenge: true
- title: E agora?
