---
hero_image: images/banner.png
title: Crea el teu propi món
description: Crea el teu propi joc d’aventura obert al món
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: Introducció
  - 
    title: Mou la icona del jugador
  - 
    title: Murs massissos
  - 
    title: Mou-te pel teu món
  - 
    title: "Repte: tornar a l'habitació anterior"
    challenge: true
  - 
    title: Senyals
  - 
    title: "Repte: tresor!"
    challenge: true
  - 
    title: Gent
  - 
    title: "Repte: enemics"
    challenge: true
  - 
    title: Recullida de monedes
  - 
    title: Portes i claus
  - 
    title: "Repte: amplia el teu món"
    challenge: true
  - 
    title: "I ara què ve?"
