---
hero_image: images/create-your-own-world.png
title: Stwórz własny świat
description: Naucz się, jak stworzyć własną grę przygodową.
listed: true
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Stwórz własny świat
  - 
    title: Move the player sprite
  - 
    title: Solid walls
  - 
    title: Move around your world
  - 
    title: "Challenge: move back to the previous room"
    challenge: true
  - 
    title: Znaki
  - 
    title: "Wyzwanie: skarb!"
    challenge: true
  - 
    title: Postacie
  - 
    title: "Wyzwanie: wrogowie"
    challenge: true
  - 
    title: Collect coins
  - 
    title: Drzwi i klucze
  - 
    title: "Wyzwanie: rozwiń swój świat"
    challenge: true
  - 
    title: "What next?"
