---
hero_image: images/create-your-own-world.png
title: Stwórz własny świat
description: Naucz się, jak stworzyć własną grę przygodową.
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: Wprowadzenie
  - 
    title: Przesuń duszka gracza
  - 
    title: Solidne ściany
  - 
    title: Poruszaj się po swoim świecie
  - 
    title: "Wyzwanie: wróć do poprzedniego pokoju"
    challenge: true
  - 
    title: Znaki
  - 
    title: "Wyzwanie: skarb!"
    challenge: true
  - 
    title: Osoby
  - 
    title: "Wyzwanie: wrogowie"
    challenge: true
  - 
    title: Zbieraj monety
  - 
    title: Drzwi i klucze
  - 
    title: "Wyzwanie: rozwiń swój świat"
    challenge: true
  - 
    title: "Co dalej?"
