---
hero_image: images/banner.png
title: Vytvor si svoj svet
description: Vytvorte si vlastnú adventúru otvoreného sveta
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: Úvod
  - 
    title: Presuňte prehrávač scény
  - 
    title: Pevné steny
  - 
    title: Presuňte sa okolo sveta
  - 
    title: "Výzva: vráťte sa späť do predchádzajúcej miestnosti"
    challenge: true
  - 
    title: Značky
  - 
    title: "Výzva: poklad!"
    challenge: true
  - 
    title: Ľudia
  - 
    title: "Výzva: nepriatelia"
    challenge: true
  - 
    title: Zbierať mince
  - 
    title: Dvere a kľúče
  - 
    title: "Výzva: rozšírte svoj svet"
    challenge: true
  - 
    title: "Čo ďalej?"
