---
hero_image: images/create-your-own-world.png
title: Kreiraj sopstveni svijet
description: Nauči kako da napraviš sopstvenu igru avanture u otvorenom svijetu.
listed: true
copyedit: false
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Šta će ti biti potrebno
  - 
    title: Pomjeranje lika igrača
  - 
    title: Čvrsti zidovi
  - 
    title: "Programiranje tvog svijeta"
    challenge: true
  - 
    title: Znakovi
  - 
    title: "Izazov: blago!"
    challenge: true
  - 
    title: Osobe
  - 
    title: "Izazov: neprijatelji"
    challenge: true
  - 
    title: Sakupljanje novčića
  - 
    title: Vrata i ključevi
  - 
    title: "Izazov: proširi svoj svijet"
    challenge: true
  - 
    title: "What next?"
