---
hero_image: images/create-your-own-world.png
title: Crée ton propre monde
description: Crée ton propre monde pour un jeu d'aventure
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
- title: Introduction
- title: Déplace le sprite du joueur
- title: Murs solides
  completion:
  - engaged
- title: Déplace-toi dans ton monde
- title: 'Défi: revenir à la salle précédente'
  challenge: true
- title: Panneaux
- title: 'Défi: trésor!'
  challenge: true
- title: Les personnes
- title: 'Défi: ajoute un ennemi'
  challenge: true
- title: Collecter des pièces
- title: Les portes et les clés
  completion:
  - internal
- title: 'Défi: étends ton monde'
  challenge: true