hero_image: images/create-your-own-world.png
title: Crées ton propre monde
description: Apprends à programmer ton propre monde pour un jeu d'aventure.
original_url: https://codeclubprojects.org/en-GB/scratch/create-your-own-world
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Coder votre joueur
- title: Coder votre monde
- title: Signalisations
- title: Les gens
- title: Collecter des pièces
- title: Portes et clés
