---
hero_image: images/create-your-own-world.png
title: Créer ton propre monde
description: Apprends à programmer ton propre monde pour un jeu d'aventure.
listed: true
copyedit: false
version: 4
last_tested: 2018-10-23
steps:
  - 
    title: Introduction
  - 
    title: Coder votre joueur
  - 
    title: Murs solides
  - 
    title: Signalisations
  - 
    title: "Les gens"
    challenge: true
  - 
    title: Panneaux
  - 
    title: "Challenge: trésor !"
    challenge: true
  - 
    title: Personnes
  - 
    title: "Challenge: ennemis"
    challenge: true
  - 
    title: Collect coins
  - 
    title: Les portes et les clés
  - 
    title: "Challenge: Élargir ton monde"
    challenge: true
  - 
    title: "Défi : plus de crayons"
