---
hero_image: images/create-your-own-world.png
title: Crea il Tuo Mondo
description: Scopri come creare il tuo gioco di avventura open-world.
original_url: https://codeclubprojects.org/en-GB/scratch/create-your-own-world
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Spostare lo sprite del giocatore
  - 
    title: Muri solidi
  - 
    title: Programmare il tuo mondo
  - 
    title: Cartelli
  - 
    title: 'Sfida: tesoro!'
  - 
    title: Persone
  - 
    title: 'Sfida: nemici'
  - 
    title: Raccogliere monete
  - 
    title: Porte e chiavi
  - 
    title: 'Sfida: espandi il tuo mondo'
