---
hero_image: images/banner.png
title: Crea il Tuo Mondo
description: Scopri come creare il tuo gioco di avventura esplorativa
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
  - 
    title: Introduzione
  - 
    title: Spostare lo sprite del giocatore
  - 
    title: Muri solidi
    completion:
      - engaged
  - 
    title: Muoviti nel tuo mondo
  - 
    title: 'Sfida: trasferirsi nella stanza precedente'
    challenge: true
  - 
    title: Cartelli
  - 
    title: 'Sfida: tesoro!'
    challenge: true
  - 
    title: Persone
  - 
    title: 'Sfida: nemici'
    challenge: true
  - 
    title: Raccogliere monete
  - 
    title: Porte e chiavi
    completion:
      - internal
  - 
    title: 'Sfida: espandi il tuo mondo'
    challenge: true
  - 
    title: E poi?
