---
hero_image: images/banner.png
title: Crea il Tuo Mondo
description: Scopri come creare il tuo gioco di avventura esplorativa
listed: true
copyedit: false
version: 4.1.0
last_tested: 2018-10-23
steps:
- title: Introduzione
  completion: engaged
- title: Codifica il tuo giocatore
- title: Muri solidi
- title: Muoviti nel tuo mondo
- title: 'Sfida: trasferirsi nella stanza precedente'
  challenge: true
- title: Cartelli
- title: 'Sfida: tesoro!'
  challenge: true
- title: Persone
- title: 'Sfida: nemici'
  challenge: true
- title: Raccogliere monete
  completion: internal
- title: Porte e chiavi
- title: 'Sfida: espandi il tuo mondo'
  challenge: true
- title: E poi?
